IncityApp.Web/Areas/Backoffice/Controllers/LicenseCategoryController.cs
using IncityApp.BLL;
using IncityApp.Models;
using Engine;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace IncityApp.Controllers
{
    [Area("Backoffice")]
    [Authorize(Policy = "Admin")]
    public class LicenseCategoryController : Controller
    {
        private string pageName = "License Category";

        private ILicenseCategoryService licenseCategoryService;
        private IAdminLogService adminLogService;

        public LicenseCategoryController(ILicenseCategoryService _licenseCategoryService, IAdminLogService _adminLogServie)
        {
            licenseCategoryService = _licenseCategoryService;
            adminLogService = _adminLogServie;
        }

        // Initiate new object
        private LicenseCategory NewObject()
        {
            LicenseCategory licenseCategory = new LicenseCategory();
            licenseCategory.IsActive = true;
            licenseCategory.IsDeleted = false;
            licenseCategory.CreateDate = DateTime.Now;
            licenseCategory.CreateBy = User.Identity.Name;
            licenseCategory.LastUpdate = DateTime.Now;
            licenseCategory.LastUser = User.Identity.Name;
            licenseCategory.Remark = "";

            return licenseCategory;
        }

        // Load existing object
        private LicenseCategory LoadObject(int id = 0)
        {
            LicenseCategory licenseCategory = new LicenseCategory();
            if (id != 0)
            {
                licenseCategory = licenseCategoryService.GetActive(id, out string ErrMsg);
                licenseCategory.LastUpdate = DateTime.Now;
                licenseCategory.LastUser = User.Identity.Name;

                if (ErrMsg != "")
                {
                    ModelState.AddModelError(pageName, ErrMsg);
                }
            }

            return licenseCategory;
        }

        // Index page
        public IActionResult Index(string trash, string delete, string restore)
        {
            if (trash != "1")
            {
                ViewData["Title"] = pageName + " Listing";

                ViewBag.LicenseCategoryList = licenseCategoryService.GetActiveList(out string ErrMsg);

                if (ErrMsg != "")
                {
                    ModelState.AddModelError(pageName, ErrMsg);
                }
                else
                {
                    List<LicenseCategory> list = licenseCategoryService.GetDeletedList(out ErrMsg);

                    if (ErrMsg != "")
                    {
                        ModelState.AddModelError(pageName, ErrMsg);
                    }
                    else
                    {
                        ViewBag.TrashCount = list.Count();
                    }
                }
            }
            else
            {
                ViewData["Title"] = "Trash List: " + pageName;

                List<LicenseCategory> list = licenseCategoryService.GetDeletedList(out string ErrMsg);

                if (ErrMsg != "")
                {
                    ModelState.AddModelError(pageName, ErrMsg);
                }
                else
                {
                    ViewBag.LicenseCategoryList = list;
                    ViewBag.IsTrash = trash;
                }
            }

            if (delete == "1")
            {
                ViewBag.SucMsg = "Successfully delete."; 
            }
            else if (delete == "2")
            {
                ViewBag.SucMsg = "Successfully delete permanant.";
            }

            if (restore == "1")
            {
                ViewBag.SucMsg = "Successfully restore.";
            }

            return View();
        }

        // Create
        public IActionResult Create()
        {
            ViewData["Title"] = "Create " + pageName;
            LicenseCategory licenseCategory = NewObject();

            return View(licenseCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(LicenseCategory licenseCategory)
        {
            if (ModelState.IsValid)
            {
                licenseCategoryService.Create(licenseCategory, out string ErrMsg);

                if (ErrMsg != "")
                {
                    ModelState.AddModelError(pageName, ErrMsg);

                    adminLogService.Create("Create (Id: " + licenseCategory.Id + ")", pageName, HttpUtil.GetIPAddress(HttpContext), ErrMsg, out string ErrMsg2);

                    if(ErrMsg2 != "")
                    {
                        ViewBag.ErrMsg = "Warning: Failed to create admin log.";
                    }

                    return View();
                }
                else
                {
                    ViewBag.SucMsg = "Succesfully";

                    adminLogService.Create("Create (Id: " + licenseCategory.Id + ")", pageName, HttpUtil.GetIPAddress(HttpContext), "Successfully", out string ErrMsg2);

                    if (ErrMsg2 != "")
                    {
                        ViewBag.ErrMsg = "Warning: Failed to create admin log.";
                    }

                    licenseCategory = NewObject();
                    ModelState.Clear();
                    return View(licenseCategory);
                }
            }

            return View();
        }

        // Edit
        public IActionResult Edit(int id = 0)
        {
            ViewData["Title"] = "Edit " + pageName;
            LicenseCategory licenseCategory = LoadObject(id);

            return View(licenseCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(LicenseCategory licenseCategory)
        {
            if (ModelState.IsValid)
            {
                licenseCategoryService.Edit(licenseCategory, out string ErrMsg);

                if (ErrMsg != "")
                {
                    ModelState.AddModelError(pageName, ErrMsg);

                    adminLogService.Create("Edit (Id: " + licenseCategory.Id + ")", pageName, HttpUtil.GetIPAddress(HttpContext), ErrMsg, out string ErrMsg2);

                    if (ErrMsg2 != "")
                    {
                        ViewBag.ErrMsg = "Warning: Failed to create admin log.";
                    }

                    return View();
                }
                else
                {
                    ViewBag.SucMsg = "Succesfully";

                    adminLogService.Create("Edit (Id: " + licenseCategory.Id + ")", pageName, HttpUtil.GetIPAddress(HttpContext), "Successfully", out string ErrMsg2);

                    if (ErrMsg2 != "")
                    {
                        ViewBag.ErrMsg = "Warning: Failed to create admin log.";
                    }

                    return View();
                }
            }

            return View();
        }

        // Delete
        public IActionResult Delete(int id, string trash)
        {
            LicenseCategory licenseCategory = LoadObject(id);

            if (trash == "1")
            {
                ViewBag.Permanant = "1";
            }
            else
            {
                ViewBag.Permanant = "0";
            }

            return View(licenseCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, int permanant)
        {
            if (permanant == 0)
            {
                licenseCategoryService.Delete(id, out string ErrMsg);

                if (ErrMsg != "")
                {
                    ModelState.AddModelError(pageName, ErrMsg);

                    adminLogService.Create("Delete (Id: " + id + ")", pageName, HttpUtil.GetIPAddress(HttpContext), ErrMsg, out string ErrMsg2);

                    if (ErrMsg2 != "")
                    {
                        ViewBag.ErrMsg = "Warning: Failed to create admin log.";
                    }

                    return View();
                }
                else
                {
                    ViewBag.SucMsg = "Succesfully";

                    adminLogService.Create("Successfully Delete (Id: " + id + ")", pageName, HttpUtil.GetIPAddress(HttpContext), "Successfully", out string ErrMsg2);

                    if (ErrMsg2 != "")
                    {
                        ViewBag.ErrMsg = "Warning: Failed to create admin log.";
                    }

                    return RedirectToAction("Index", new { delete = "1" });
                }
            }
            else
            {
                licenseCategoryService.DeletePermanant(id, out string ErrMsg);

                if (ErrMsg != "")
                {
                    ModelState.AddModelError(pageName, ErrMsg);

                    adminLogService.Create("Delete Permanant (Id: " + id + ")", pageName, HttpUtil.GetIPAddress(HttpContext), ErrMsg, out string ErrMsg2);

                    if (ErrMsg2 != "")
                    {
                        ViewBag.ErrMsg = "Warning: Failed to create admin log.";
                    }

                    return View();
                }
                else
                {
                    ViewBag.SucMsg = "Succesfully";

                    adminLogService.Create("Delete Permanant (Id: " + id + ")", pageName, HttpUtil.GetIPAddress(HttpContext), "Successfully", out string ErrMsg2);

                    if (ErrMsg2 != "")
                    {
                        ViewBag.ErrMsg = "Warning: Failed to create admin log.";
                    }

                    return RedirectToAction("Index", new { trash = "1", delete = "2" });
                }
            }
        }

        // Restore
        public IActionResult Restore(int id)
        {
            LicenseCategory licenseCategory = LoadObject(id);

            return View(licenseCategory);
        }

        [HttpPost]

IncityApp.Web/Areas/Backoffice/Views/LicenseCategory/Create.cshtml
@model IncityApp.Models.LicenseCategory

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@ViewData["Title"]</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboard", "Dashboard")">Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "LicenseCategory")">License Category</a>
            </li>
            <li class="active">
                <strong>Create License Category</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">

            @if (ViewBag.ErrMsg != "")
            {
                <div class="view-success">@Html.Raw(ViewBag.SucMsg)</div>
            }

            <div class="view-error">@Html.ValidationSummary()</div>

            @if (ViewBag.ErrMsg != "")
            {
                <div class="view-error">@Html.Raw(ViewBag.ErrMsg)</div>
            }

            <div class="ibox float-e-margins">
                @*<div class="ibox-title">
                <h5>Basic</h5>
            </div>*@
                <div class="ibox-content">
                    @using (Html.BeginForm("Create", "LicenseCategory", FormMethod.Post, new { @class = "form-horizontal" }))
                    {
                        @Html.HiddenFor(p => p.Id)
                        @Html.HiddenFor(p => p.IsDeleted)
                        @Html.HiddenFor(p => p.CreateBy)
                        @Html.HiddenFor(p => p.CreateDate)
                        @Html.HiddenFor(p => p.LastUpdate)
                        @Html.HiddenFor(p => p.LastUser)
                        @Html.HiddenFor(p => p.Remark)
                        <div class="form-group">
                            <label class="col-sm-2 control-label">@Html.DisplayNameFor(p => p.Name)</label>

                            <div class="col-sm-8">
                                @Html.TextBoxFor(p => p.Name, new { @Class = "form-control" })
                                <div class="checkbox"><label>@Html.EditorFor(p => p.IsActive) @Html.DisplayNameFor(p => p.IsActive)</label></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">@Html.DisplayNameFor(p => p.Description)</label>
                            <div class="col-sm-8">@Html.TextAreaFor(p => p.Description, new { @Class = "form-control" })</div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <a class="btn btn-white" href="@Url.Action("Index")">Cancel</a>
                                <button class="btn btn-primary" type="submit">Save changes</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="~/lib/iCheck/custom.css" />
}

@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/lib/iCheck/icheck.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {

            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });

        });
    </script>
}

IncityApp.Web/Areas/Backoffice/Views/LicenseCategory/Delete.cshtml
@model IncityApp.Models.LicenseCategory

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@ViewData["Title"]</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboard", "Dashboard")">Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "LicenseCategory")">License Category</a>
            </li>
            <li class="active">
                <strong>Delete License Category</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">

            @if (ViewBag.ErrMsg != "")
            {
                <div class="view-success">@Html.Raw(ViewBag.SucMsg)</div>
            }

            <div class="view-error">@Html.ValidationSummary()</div>

            @if (ViewBag.ErrMsg != "")
            {
                <div class="view-error">@Html.Raw(ViewBag.ErrMsg)</div>
            }

            <div class="ibox float-e-margins">
                @*<div class="ibox-title">
                <h5>Basic</h5>
            </div>*@
                <div class="ibox-content">
                    @using (Html.BeginForm("Delete", "LicenseCategory", FormMethod.Post, new { @class = "form-horizontal", @style = "padding-left: 20px;" }))
                    {
                        @Html.Hidden("id", Model.Id)
                        @Html.Hidden("permanant", (String)ViewBag.Permanant)
                        <div class="form-group">
                            <h1>Deleting @Model.Name</h1>

                            @if (ViewBag.Permanant == "0")
                            {
                                <label>Confirm delete this? It will be move to the trash list.</label>
                            }
                            else
                            {
                                <label>Confirm permanantly delete this? It will be remove from the system and this action CANNOT be roll back.</label>
                            }
                        </div>
                        <br />
                        <div class="form-group">
                            <div>
                                <button class="btn btn-white"><a href="@Url.Action("Index")">Cancel</a></button>
                                <button class="btn btn-primary" type="submit">Confirm</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="~/lib/iCheck/custom.css" />
}

@section Scripts {
    <environment names="Development,Staging,Productio">
        <script src="~/lib/iCheck/icheck.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {

            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });

        });
    </script>
}

IncityApp.Web/Areas/Backoffice/Views/LicenseCategory/Edit.cshtml
@model IncityApp.Models.LicenseCategory

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@ViewData["Title"]</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboard", "Dashboard")">Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "LicenseCategory")">License Category</a>
            </li>
            <li class="active">
                <strong>Edit License Category</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">

            @if (ViewBag.ErrMsg != "")
            {
                <div class="view-success">@Html.Raw(ViewBag.SucMsg)</div>
            }

            <div class="view-error">@Html.ValidationSummary()</div>

            @if (ViewBag.ErrMsg != "")
            {
                <div class="view-error">@Html.Raw(ViewBag.ErrMsg)</div>
            }

            <div class="ibox float-e-margins">
                @*<div class="ibox-title">
                <h5>Basic</h5>
            </div>*@
                <div class="ibox-content">
                    @using (Html.BeginForm("Edit", "LicenseCategory", FormMethod.Post, new { @class = "form-horizontal" }))
                    {
                        @Html.HiddenFor(p => p.Id)
                        @Html.HiddenFor(p => p.IsDeleted)
                        @Html.HiddenFor(p => p.CreateBy)
                        @Html.HiddenFor(p => p.CreateDate)
                        @Html.HiddenFor(p => p.Remark)
                        <div class="form-group">
                            <label class="col-sm-2 control-label">@Html.DisplayNameFor(p => p.Name)</label>

                            <div class="col-sm-8">
                                @Html.TextBoxFor(p => p.Name, new { @Class = "form-control" })
                                <div class="checkbox"><label>@Html.EditorFor(p => p.IsActive) @Html.DisplayNameFor(p => p.IsActive)</label></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">@Html.DisplayNameFor(p => p.Description)</label>
                            <div class="col-sm-8">@Html.TextAreaFor(p => p.Description, new { @Class = "form-control" })</div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-white"><a href="@Url.Action("Index")">Cancel</a></button>
                                <button class="btn btn-primary" type="submit">Save changes</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="~/lib/iCheck/custom.css" />
}

@section Scripts {
    <environment names="Development,Staging,Productio">
        <script src="~/lib/iCheck/icheck.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {

            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });

        });
    </script>
}

IncityApp.Web/Areas/Backoffice/Views/LicenseCategory/Index.cshtml
@model IncityApp.Models.LicenseCategory

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@ViewData["Title"]</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboard", "Index")">Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "LicenseCategory")">License Category</a>
            </li>
            <li class="active">
                <strong>@ViewData["Title"]</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2 right">
        <button type="button" class="btn btn-w-m btn-primary"><a href="@Url.Action("Create", "LicenseCategory")">Create New</a></button>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">

            @if (ViewBag.SucMsg != "")
            {
                <div class="view-success">@Html.Raw(ViewBag.SucMsg)</div>
            }

            @if (ViewBag.ErrMsg != "")
            {
                <div class="view-error">@Html.Raw(ViewBag.ErrMsg)</div>
            }

            <div class="ibox float-e-margins">
                <div class="ibox-content">

                    <table class="table table-striped table-bordered table-hover dataTables-example">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(p => p.Name)</th>
                                <th>@Html.DisplayNameFor(p => p.IsActive)</th>
                                <th>@Html.DisplayNameFor(p => p.LastUpdate)</th> @* Edit the "order" option in datatable script below to make sure it is order by last update by default. *@ 
                                <th>@Html.DisplayNameFor(p => p.LastUser)</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (LicenseCategory licenseCategory in (List<LicenseCategory>)ViewBag.LicenseCategoryList)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(p => licenseCategory.Name)</td>
                                    <td>@Html.DisplayFor(p => licenseCategory.IsActive)</td>
                                    <td>@Html.DisplayFor(p => licenseCategory.LastUpdate)</td>
                                    <td>@Html.DisplayFor(p => licenseCategory.LastUser)</td>
                                    @if (ViewBag.IsTrash != "1")
                                    {
                                        <td><a href="@Url.Action("Edit", new { id = licenseCategory.Id })">Edit</a> | <a href="@Url.Action("Delete", new { id = licenseCategory.Id })">Delete</a></td>
                                    }
                                    else
                                    {
                                        <td><a href="@Url.Action("Restore", new { id = licenseCategory.Id })">Restore</a> | <a href="@Url.Action("Delete", new { id = licenseCategory.Id, trash = "1" })">Delete</a></td>
                                    }
                                </tr>
                            }
                        </tbody>
                    </table>

                    @if (ViewBag.IsTrash != "1")
                    {
                        <a class="trash-link" href="@Url.Action("Index", new { trash = "1" })">Trash List (@ViewBag.TrashCount)</a>
                    }
                    else
                    {
                        <a class="trash-link back" href="@Url.Action("Index")">Back To List</a>
                    }
                </div>
            </div>
        </div>
    </div>

</div>

@section Styles {
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/dataTables/datatables.min.css" />
    </environment>
}

@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/lib/dataTables/datatables.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {

            $('.dataTables-example').DataTable({
                pageLength: 25,
                columnDefs: [{ "type": "date", "targets": 2 }],
                order: [[2, "desc"]],
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel' },
                    { extend: 'pdf' },

                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                        }
                    }
                ]

            });


        });

      
    </script>
}

IncityApp.Web/Areas/Backoffice/Views/LicenseCategory/Restore.cshtml
@model IncityApp.Models.LicenseCategory

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@ViewData["Title"]</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboard", "Dashboard")">Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "LicenseCategory")">License Category</a>
            </li>
            <li class="active">
                <strong>Restore License Category</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">

            @if (ViewBag.ErrMsg != "")
            {
                <div class="view-success">@Html.Raw(ViewBag.SucMsg)</div>
            }

            <div class="view-error">@Html.ValidationSummary()</div>

            @if (ViewBag.ErrMsg != "")
            {
                <div class="view-error">@Html.Raw(ViewBag.ErrMsg)</div>
            }

            <div class="ibox float-e-margins">
                @*<div class="ibox-title">
                <h5>Basic</h5>
            </div>*@
                <div class="ibox-content">
                    @using (Html.BeginForm("Restore", "LicenseCategory", FormMethod.Post, new { @class = "form-horizontal", @style = "padding-left: 20px;" }))
                    {
                        @Html.Hidden("id", Model.Id)
                        @Html.Hidden("trash", "1")
                        <div class="form-group">
                            <h1>Restore @Model.Name</h1>

                            <label>Confirm restore this? It will be move to the active list.</label>
                        </div>
                        <br />
                        <div class="form-group">
                            <div>
                                <button class="btn btn-white"><a href="@Url.Action("Index")">Cancel</a></button>
                                <button class="btn btn-primary" type="submit">Confirm</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="~/lib/iCheck/custom.css" />
}

@section Scripts {
    <environment names="Development,Staging,Productio">
        <script src="~/lib/iCheck/icheck.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {

            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });

        });
    </script>
}